AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/rdf2marc/model2marc/*field_*_spec.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'lambda-*/lambda_function.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'lib/rdf2marc/model2marc/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/rdf2marc/model2marc/field.rb'

Style/Documentation:
  Exclude:
    - 'lib/array.rb'
    - 'lib/hash.rb'

Style/DocumentDynamicEvalDefinition:
  Enabled: false
