version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler -v 2.1.4
      - run:
          name: Install gem dependencies
          command: bundle check || bundle install
      - run:
          name: Lint using rubocop
          command: bundle exec rubocop
      - run:
          name: Run RSpec test suite
          command: bundle exec rspec
workflows:
  version: 2

  test:
    jobs:
      - test