version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4
references:
  default_ruby_version: &default_ruby_version 2.7-browsers
  ruby_envs: &ruby_envs
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
executors:
  default:
    parameters:
      ruby_tag:
        description: "The `cimg/ruby` Docker image version tag."
        type: string
        default: *default_ruby_version
    docker:
      - image: cimg/ruby:<< parameters.ruby_tag >>
        <<: *ruby_envs
jobs:
  build:
    executor: default
    steps:
      - checkout
      - ruby/install-deps:
          key: rdf2marc
  linting:
    executor: default
    steps:
      - checkout
      - ruby/install-deps:
          key: rdf2marc
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    executor: default
    steps:
      - checkout
      - ruby/install-deps:
          key: rdf2marc
      - run:
          name: Run tests in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress
      - store_test_results:
          path: test_results
workflows:
  version: 2
  build:
    jobs:
      - build
      - linting:
          requires:
            - build
      - test:
          requires:
            - build
