#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
$LOAD_PATH.unshift 'lib'

require 'rdf2marc'

if ARGV.length == 1
  instance_graph, work_graph, admin_metadata_graph = Rdf2marc::GraphsLoader.from_instance_uri(ARGV[0])
elsif ARGV.length == 3
  instance_graph = Rdf2marc::GraphsLoader.from_path(ARGV[0])
  work_graph = Rdf2marc::GraphsLoader.from_path(ARGV[1])
  admin_metadata_graph = Rdf2marc::GraphsLoader.from_path(ARGV[2])
else
  puts 'Usage: rdf2model <instance ttl file> <work ttl file> <admin metadata ttl file>'
  puts 'Usage: rdf2model <instance uri>'
  exit(false)
end

record_model = Rdf2marc::Rdf2model.to_model(instance_graph, work_graph, admin_metadata_graph)
puts JSON.pretty_generate(record_model.to_h)
