#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
$LOAD_PATH.unshift 'lib'

require 'rdf2marc'

if ARGV.empty?
  puts 'Usage: rdf2model <instance ttl file> <work ttl file?> <admin metadata ttl file?>'
  puts 'Usage: rdf2model <instance uri>'
  exit(false)
end

record_model = if ARGV.length == 1 && ARGV[0].start_with?('http')
                 Rdf2marc::Converter.convert(url: ARGV[0])
               else
                 Rdf2marc::Converter.convert(files: ARGV)
               end
puts JSON.pretty_generate(record_model.to_h)
