#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift 'lib'
require 'rdf2marc'

if ARGV.empty?
  puts 'Usage: rdf2marc <instance ttl file> <work ttl file?> <admin metadata ttl file?>'
  puts 'Usage: rdf2marc <instance uri>'
  exit(false)
end

record_model = if ARGV.length == 1 && ARGV[0].start_with?('http')
                 Rdf2marc::Converter.convert(url: ARGV[0])
               else
                 Rdf2marc::Converter.convert(files: ARGV)
               end

marc_record = Rdf2marc::Model2marc::Record.new(record_model)
puts marc_record.to_s
writer = MARC::Writer.new('record.mar')
writer.write(marc_record.marc_record)
writer.close
